# Generated by Django 5.0 on 2024-08-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_customuser_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(max_length=500, upload_to="user_files"),
        ),
    ]
