# Generated by Django 5.0 on 2024-08-22 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_document_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="birth_date",
            field=models.CharField(blank=True, default="2024-08-22", max_length=100),
        ),
        migrations.CreateModel(
            name="Representative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=250, null=True)),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
                ("email", models.EmailField(blank=True, max_length=250, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="representative",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
