# Generated by Django 5.0 on 2024-08-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_customuser_birth_date_representative"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="birth_date",
            field=models.CharField(blank=True, default="2024-08-23", max_length=100),
        ),
    ]
